require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - tmp/**/*
    - vendor/**/*
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 2.4

# Use older RuboCop default
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': ()

# SupportedStyles: percent, brackets
Style/SymbolArray:
  EnforcedStyle: brackets

# Code is currently broken with frozen string literal comments applied.
# TODO: Enable and fix build
Style/FrozenStringLiteralComment:
  Enabled: false

# Be relatively lenient with line length
Layout/LineLength:
  Max: 94

inherit_from: .rubocop_todo.yml
